add wave -position 1 /tb_washing_machine_controller/rst_n
add wave -position 2 /tb_washing_machine_controller/clk
add wave -position 3 /tb_washing_machine_controller/clk_freq
add wave -position 4 /tb_washing_machine_controller/coin_in
add wave -position 5 /tb_washing_machine_controller/double_wash
add wave -position 6 /tb_washing_machine_controller/timer_pause
add wave -position 7 /tb_washing_machine_controller/wash_done
add wave -position 8 /tb_washing_machine_controller/DUT/state
add wave -position 9 /tb_washing_machine_controller/DUT/clock_count 